export const GOING_GUEST_NAMES = [
  "Aaron Hubbard",
  "Adrian",
  "Adrienne Wong",
  "Alexandra K Wolfe",
  "Alicia Z",
  "Andrew Nowicki",
  "Anne Richards",
  "Annie Ling",
  "Ariana Grande",
  "Auguste Fallon",
  "Bart",
  "Belinda Huang",
  "Cara Takemoto",
  "Caroline Berger",
  "Conor Doyle",
  "Cory Nelund",
  "Deep",
  "Drew Kim",
  "em king",
  "Emily Aldridge",
  "Emma Zhou",
  "Frances Liu",
  "Frances Liu's +1",
  "Gabriel Briscoe",
  "Geri W",
  "Hannah",
  "Hao",
  "Holly",
  "Ian",
  "Elise",
  "Jane Wong",
  "Jared",
  "Jeff H",
  "Jerry Wang",
  "Allison Lee",
  "Jess",
  "Jim",
  "John Shen",
  "Johnny Hung",
  "Jordan F Morris",
  "Kannan Goundan",
  "Kate Laux",
  "Kate Laux's +1",
  "Kavya",
  "Michael Filippakis",
  "Keefer Taylor",
  "Kelly Wong",
  "Kelly Wong's +1",
  "Ken Bongort",
  "ki",
  "Mala",
  "Marco Dyer",
  "Mariah Bush",
  "Max Li",
  "Monica Greenwald",
  "N8",
  "Nancy",
  "Nicole Huang",
  "Niloo H",
  "Noah",
  "Paul Yang",
  "Ross Fischer",
  "Ross F",
  "Ruby",
  "Sam Zeitlin",
  "Sara Taylor",
  "Shane",
  "Shilpa Lokareddy",
  "Varun Srinivasan",
  "Simi",
  "Gopal",
  "Stuti Pandey",
  "Theresa Cheng",
  "Vina Levin",
  "Yasha"
];
